### ISSUE TITLE
Default isInEuropeanUnion to false in case of NoSuchMethodError

### ISSUE THREAD

**Issue by chuwy** [snowplow/scala-maxmind-iplookups#123]
In Spark Enrich we need to use an older version of geoip2 because of binary incompatibility between its version of Jackson (2.9) and Spark's (2.6). As a result when we updated scala-maxmind-iplookups to 0.6.0, it threw a `NoSuchMethodError` because it now has [new](https://github.com/maxmind/GeoIP2-java/releases/tag/v2.11.0) `isInEuropeanUnion` property. Not used in our output however.

**Comment by chuwy** [comment]
Was added in https://github.com/snowplow/scala-maxmind-iplookups/pull/101
